checks:
  exclude:
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "no-anti-affinity"
    - "default-service-account"
    - "sensitive-host-mounts"
    - "latest-tag"
