apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1  # Single instance for lab, increase for HA

  # Enable superuser access for database initialization jobs
  enableSuperuserAccess: true

  # PostgreSQL version
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  # Storage - using Longhorn for persistence
  storage:
    size: 10Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  # Bootstrap with initial databases
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: postgres-credentials

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # S3 Backup configuration
  # Placeholders are replaced by generate-secrets.sh from .env values
  backup:
    barmanObjectStore:
      destinationPath: s3://etcdme/postgres
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: s3-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 2
      data:
        compression: gzip
    retentionPolicy: "30d"
  # Secret postgres-credentials is defined in overlay secrets.sops.yaml
  # Secret s3-backup-credentials is defined in overlay secrets.sops.yaml
