# n8n workflow automation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.8
    helm:
      valuesObject:
        # Disable embedded PostgreSQL
        postgresql:
          enabled: false
        # Use PostgreSQL database type
        db:
          type: postgresdb
        # External PostgreSQL configuration
        externalPostgresql:
          host: postgres-rw.postgres.svc.cluster.local
          port: 5432
          database: n8n
          username: n8n
          existingSecret: n8n-postgres
        # Encryption key from secret
        existingEncryptionKeySecret: n8n-encryption
        # Timezone
        timezone: Europe/Paris
        # Main container config
        main:
          # Disable n8n built-in auth (oauth2-proxy handles it)
          extraEnvVars:
            N8N_USER_MANAGEMENT_DISABLED: "true"
        # Ingress disabled (using gateway)
        ingress:
          enabled: false
        # Service config
        service:
          enabled: true
          type: ClusterIP
          port: 5678
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Probe configuration - give n8n more time to start
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
